import type { Channel } from '@campaign/shared';
import type { Db } from './deps.ts';
import { isProviderName, type ProviderName } from './registry.ts';

/**
 * The sending identity a deployment can state without a database row.
 *
 * `provider_credentials` is the real answer, and it stays the real answer: it is
 * per tenant, its secret is encrypted at rest, and iterating every ACTIVE row is
 * what I11 is about. This file is the fallback for the one situation that table
 * cannot serve — a single-tenant deployment whose entire configuration is a
 * platform's environment-variable panel, with no seeded credential row and nobody
 * logged in to create one.
 *
 * Before this existed, `SEND_MODE=live` with a perfectly good SMTP_HOST in the
 * environment sent nothing at all. `resolveSender` found no credential row,
 * returned undefined, and every message was cancelled with `no_recipient_address`
 * — a reason code that is true (there was no sender) and completely useless (the
 * operator had configured one). The failure was silent, correct, and impossible to
 * diagnose from the outside, which is the worst combination available.
 *
 * Precedence, deliberately: the DATABASE ROW WINS. A tenant that has configured a
 * sender through the UI must not have it quietly overridden by a stray environment
 * variable on the host. This is consulted only when the row is absent.
 */

export type EnvSender = {
  readonly provider: ProviderName;
  readonly fromAddress: string;
};

/**
 * Why each channel has an ORDER rather than a set.
 *
 * A deployment can legitimately hold credentials for two email providers at once
 * — a Postmark token left over from an experiment, an SMTP relay actually in use.
 * Picking arbitrarily between them means the sending domain changes on a restart,
 * which is how a reputable domain acquires a spam reputation it cannot explain.
 * SMTP first, because it is the one every free tier speaks.
 */
export function senderFromEnv(
  channel: Channel,
  env: NodeJS.ProcessEnv = process.env,
): EnvSender | undefined {
  const set = (name: string): string | undefined => {
    const value = env[name];
    return value !== undefined && value.trim() !== '' ? value.trim() : undefined;
  };

  if (channel === 'email') {
    const smtpFrom = set('SMTP_FROM');
    if (set('SMTP_HOST') && smtpFrom) return { provider: 'smtp', fromAddress: smtpFrom };

    const postmarkFrom = set('POSTMARK_FROM');
    if (set('POSTMARK_SERVER_TOKEN') && postmarkFrom) {
      return { provider: 'postmark', fromAddress: postmarkFrom };
    }
    return undefined;
  }

  const twilioFrom = set('TWILIO_FROM');
  if (set('TWILIO_ACCOUNT_SID') && set('TWILIO_AUTH_TOKEN') && twilioFrom) {
    return { provider: 'twilio', fromAddress: twilioFrom };
  }
  return undefined;
}

/**
 * What an operator needs to see on a screen when a channel is not going to work.
 *
 * Returned by the storefront's capability endpoint so a visitor is told "SMS is
 * not configured on this deployment" rather than being invited to type a phone
 * number into a form that will silently do nothing. The strings name the exact
 * variables, because "not configured" without a name is a support ticket.
 */
export function describeEnvSender(
  channel: Channel,
  env: NodeJS.ProcessEnv = process.env,
): {
  readonly configured: boolean;
  readonly provider: ProviderName | null;
  readonly detail: string;
} {
  const sender = senderFromEnv(channel, env);
  if (sender) {
    return {
      configured: true,
      provider: sender.provider,
      detail: `${sender.provider}, sending as ${sender.fromAddress}`,
    };
  }
  return {
    configured: false,
    provider: null,
    detail:
      channel === 'email'
        ? 'No email sender in the environment. Set SMTP_HOST + SMTP_FROM (any SMTP provider), or POSTMARK_SERVER_TOKEN + POSTMARK_FROM.'
        : 'No SMS sender in the environment. Set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN and TWILIO_FROM.',
  };
}

/**
 * The mock provider's simulation rates, as configuration.
 *
 * The defaults model a plausible real channel — roughly 2% hard failures and 5%
 * bounces — which is exactly right for the seeded demo, whose whole point is that
 * the analytics screens have bounces and complaints in them.
 *
 * It is wrong for the PUBLIC storefront. A stranger who places one order and lands
 * on the 5% branch concludes the project is broken, and they are not wrong to:
 * from where they are standing, a bounce and a bug look identical. A deployment
 * that hands its URL to strangers therefore sets MOCK_FAILURE_RATE=0 and
 * MOCK_BOUNCE_RATE=0 — see docs/LIVE-SENDING.md — and keeps the realism for the
 * seeded dataset, which is generated by a script rather than watched by a person.
 *
 * Returns `undefined` for anything unset, so the provider's own defaults stand.
 */
export type MockRates = {
  readonly failureRate?: number | undefined;
  readonly bounceRate?: number | undefined;
  readonly complaintRate?: number | undefined;
  readonly webhookDelayMs?: number | undefined;
};

export function mockRatesFromEnv(env: NodeJS.ProcessEnv = process.env): MockRates {
  const rate = (name: string): number | undefined => {
    const raw = env[name];
    if (raw === undefined || raw.trim() === '') return undefined;
    const parsed = Number(raw);
    // Silently ignoring a malformed rate would leave the deployment simulating
    // failures it believed it had turned off, which is the failure this whole
    // block exists to prevent.
    if (!Number.isFinite(parsed) || parsed < 0 || parsed > 1) {
      throw new Error(`${name} must be a number between 0 and 1; got '${raw}'.`);
    }
    return parsed;
  };
  const delay = Number(env['MOCK_WEBHOOK_DELAY_MS']);

  return {
    failureRate: rate('MOCK_FAILURE_RATE'),
    bounceRate: rate('MOCK_BOUNCE_RATE'),
    complaintRate: rate('MOCK_COMPLAINT_RATE'),
    webhookDelayMs: Number.isFinite(delay) && delay >= 0 ? delay : undefined,
  };
}

/**
 * The tenant's sending identity for a channel, resolved once, for both callers.
 *
 * The worker and the storefront both need this and both used to answer it with
 * their own copy of the same query. Two copies of a rule is one copy of the rule
 * plus a future disagreement, and the rule here is I11.
 *
 * I11 — READ EVERY ACTIVE CREDENTIAL, NEVER ONE ROW. The obvious implementation
 * is `ORDER BY created_at LIMIT 1`, and it is wrong in a way that only shows up on
 * the day a tenant adds a second sender: the single row it returns might name a
 * provider this build does not support, or a channel it cannot carry, and the
 * caller then dead-ends on a configuration that has a perfectly good second row
 * sitting behind it. Reading the list and walking it means an unusable credential
 * costs the tenant that credential, not the channel.
 *
 * `tests/invariants/i11-webhook-multi-credential.test.ts` scans the API source for
 * `LIMIT 1` and `queryOne` in the same block as `provider_credentials`, which is
 * how the shape of the mistake is kept out rather than just this instance of it.
 *
 * Precedence: a database row always beats the environment. A tenant that
 * configured a sender through the UI must not have it silently overridden by a
 * stray variable on the host.
 */
export async function resolveSenderFor(
  db: Db,
  opts: {
    readonly tenantId: string;
    readonly channel: Channel;
    readonly sendMode: 'off' | 'mock' | 'live';
    readonly env?: NodeJS.ProcessEnv | undefined;
  },
): Promise<{ provider: string; fromAddress: string } | undefined> {
  const env = opts.env ?? process.env;

  const { rows } = await db.query<{ provider: string; from_address: string }>(
    `SELECT provider, from_address FROM provider_credentials
      WHERE tenant_id = $1 AND channel = $2 AND is_active
      ORDER BY created_at`,
    [opts.tenantId, opts.channel],
  );
  for (const row of rows) {
    if (!isProviderName(row.provider)) continue;
    if (row.from_address.trim() === '') continue;
    return { provider: row.provider, fromAddress: row.from_address };
  }

  // No usable credential row. In mock mode that is the normal state for the seeded
  // demo, so fall back rather than refusing to send anything at all.
  if (opts.sendMode === 'mock') {
    return { provider: 'mock', fromAddress: env['MOCK_FROM'] ?? 'demo@example.com' };
  }

  // In live mode, what the environment states. A single-tenant deployment
  // configured entirely through a platform's env panel has no credential row and
  // nobody logged in to create one; without this it sent nothing and cancelled
  // every message with `no_recipient_address`, which is true and useless.
  return senderFromEnv(opts.channel, env);
}
